# Generated by Django 3.0.9 on 2021-04-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_couponcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CouponCode',
        ),
    ]
