# Generated by Django 3.0.9 on 2021-04-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_couponcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='daily_earn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='tot_referer',
            field=models.IntegerField(default=0),
        ),
    ]
