# Generated by Django 3.0.9 on 2021-05-01 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210430_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='task_earned',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='daily_earn',
            new_name='total_earned',
        ),
    ]
