# Generated by Django 3.0.9 on 2021-05-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210501_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='total_earned',
        ),
    ]
