# Generated by Django 3.0.9 on 2021-05-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_account_total_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_earned',
            field=models.IntegerField(default=0),
        ),
    ]
