# Generated by Django 3.0.9 on 2021-05-02 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_total_earned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='total_earned',
            new_name='total_balance',
        ),
    ]
