# Generated by Django 3.0.9 on 2021-04-26 11:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0002_couponcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
