# Generated by Django 3.0.9 on 2021-04-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0004_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
