# Generated by Django 3.0.9 on 2021-05-01 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0006_auto_20210430_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
