# Generated by Django 3.0.9 on 2021-05-01 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prime', '0007_auto_20210501_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prime.Vendor'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='email'),
        ),
    ]
